### ISSUE TITLE
群项目起步--序章

### ISSUE THREAD

**Issue by yessirpopesama** [0x2642/ourblog#1]
1 熟悉下github代码提交流程
2 熟悉Nodejs和mongodb代码编写
3 请继续加班

**Comment by xykbear** [comment]
# 请教主带头加班

## 请教主带头加班

### 请教主带头加班

#### 请教主带头加班

##### 请教主带头加班

**Comment by AssWeirenCan** [comment]
###### We need Mr.Lee do more overworking

**Comment by yessirpopesama** [comment]
好了 这个可以关票了
